### PR TITLE
Rel1.5

### LINKED ISSUE #174: Add support for diff on Labels
Add support for diff function to implemented for `Labels` just like `Capacities` without which sliver_diff  returns false positive/negative.

### PR DESCRIPTION
**Pull request by ibaldin**
- Changes to packaging (flit instead of -m build) 
- Update to Neo4j 5.3.0
- Addition of various features (NUMA, PTP)
- Bug fixes #174

### CODE REVIEW

**Review by kthare10 — APPROVED** [review]
Looks good!

**Comment by ibaldin** [comment]
@kthare10 could you re-approve?

**Comment by ibaldin** [comment]
Latest is `1.5.1` in PyPi

**Review by kthare10 — DISMISSED** [review]
Approved

**Comment by ibaldin** [comment]
@kthare10 can you re-re-approve :-) I think this is ready to merge to master/main

**Review by kthare10 — APPROVED** [review]
Looks good!

**Pull request merged**
